# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e49c1abce418bec2b649589bb6a8ea02022d1445bcc240e0e40b41f2c40e88d80dd3bf8c25960d2d504680717e90c423210cabb58c6f72eda09deb7e28cb42c7

test:
  secret_key_base: 246b7fa4b79c44b6e1d316b48be05f405c97eaaa8ca4b2f43a04135e61b885b41f4a08712d01bb90a3511b903f83148c215f81c05d57713bd16e863bdd03c571

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
